#!/usr/bin/env bash
# install nginx to the server
sudo apt-get update
sudo apt-get install -y nginx
server_setup="server { 
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	location / {
		try_files \$uri \$uri/ = 404;
		return 200 \"Hello World!\n\";
	}

}"

echo "$server_setup" | sudo tee /etc/nginx/sites-available/default >/dev/null
sudo service nginx restart
