#!/usr/bin/env bash
# install nginx to the server
nginx_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        return 200 \"Hello World!\n\";
    }

    location = /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }
}"

echo "$nginx_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
