#!/usr/bin/env bash
# add a redirect_me path
add_redirectme="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "\$i\\$add_redirectme" /etc/nginx/sites-available/default
sudo service nginx restart
