#!/usr/bin/env bash
# install nginx to the server
sudo apt-get update
sudo apt-get install -y nginx
server_setup="server { 
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	location / {
		try_files \$uri \$uri/ = 404;
		return 200 \"Hello World!\n\";
	}

}"

add_redirect="\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
echo "$server_setup" | sudo tee /etc/nginx/sites-available/default >/dev/null
sudo sed -i "\$i\\$add_redirect" /etc/nginx/sites-available/default
sudo service nginx restart
