#!/usr/bin/env bash
# print Best School 10 times and Bad luck on $ good luck on 8'
i=1
while ((i < 11))
do
	if ((i == 4)); then
		echo "bad luck"
	elif ((i == 8)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
