#!/usr/bin/env bash
# this prints numbers 1 to 20 and print the bad number
i=1
while ((i < 21))
do
	echo $i
	if ((i == 4)); then
		echo "bad luck from China"
	elif ((i == 9)); then
		echo "bad luck from Japan"
	elif ((i == 17)); then
		echo "bad luck from Italy"
	fi
	i=$((i+1))
done
